Module2 task1
htmlacademy-ecmascript/853355-big-trip-simple-19 pull request #4
Opened 2022-12-18 16:48 UTC by Farkhadov95

2022-12-25 22:23 UTC, andreevsm requested changes

2022-12-25 22:23 UTC, andreevsm commented on src/mock/events.js
> +    'offers': [1],
Давай выбирать id из `mockOffers`, а не рандомные числа, чтобы данные были согласованными

2022-12-25 22:23 UTC, andreevsm commented on src/mock/events.js
> +    'id': '0',
1. id же число, зачем кавычки?)
2. id является уникальным значением и не должен повторяться в других объектах массива

2022-12-25 22:23 UTC, andreevsm commented on src/presenter/events-presenter.js
> +    const pointType = mockOffers.find((offer) => offer.type === point.type);
Почему pointType, если мы находим offer?)

2022-12-25 22:23 UTC, andreevsm commented on src/presenter/events-presenter.js
> +    const eventsList = document.createElement('ul');
Хмм а это для чего? У нас все html элементы создаются через view, точнее хранятся там
Давай тогда создадим компонент для списка)

2022-12-25 22:23 UTC, andreevsm commented on src/presenter/events-presenter.js
> +    eventsListContainer.appendChild(eventsList);
Это явно лишняя логика, можно через view'шку сделать)

2022-12-25 22:23 UTC, andreevsm commented on src/presenter/events-presenter.js
> +    for (let i = 0; i < this.events.length; i++) {
Давай заменим либо на forEach либо на for of

2022-12-25 22:23 UTC, andreevsm commented on src/view/list-item-view.js
> +            <span class="event__offer-title">${offers[0].title}</span>
А почему везде `offers[0]`?

2022-12-26 20:46 UTC, andreevsm requested changes

2022-12-26 20:46 UTC, andreevsm commented on src/presenter/events-presenter.js
> +    const eventsList = document.querySelector('.trip-events__list');
Хмм ты же выше рендеришь `EventsListView`, давай его и передавать в качестве контейнера, зачем лишний раз к DOMу обращаться?)

2022-12-27 09:08 UTC, andreevsm requested changes

2022-12-27 09:08 UTC, andreevsm commented on src/presenter/events-presenter.js
> +    const eventsListContainer = document.querySelector('.trip-events');
У нас же это значение хранится в `this.eventsListContainer`, зачем мы еще раз получаем его?)

2022-12-27 09:50 UTC, Farkhadov95 commented on src/presenter/events-presenter.js
> +    const eventsListContainer = document.querySelector('.trip-events');
Точно)

2022-12-27 10:19 UTC, merged