HW 3.1
htmlacademy-ecmascript/853355-big-trip-simple-19 pull request #5
Opened 2022-12-29 14:33 UTC by Farkhadov95

2022-12-30 10:13 UTC, andreevsm requested changes

2022-12-30 10:13 UTC, andreevsm commented on src/view/add-event-view.js
> +                    <span class="event__offer-title">${offers[0].title}</span>
Хмм а почему мы так обращаемся к offers? Они ж должны рендериться исходя из количества офферов в точке)

2022-12-30 10:13 UTC, andreevsm commented on src/view/edit-event-view.js
> +              <span class="event__offer-title">${offers[0].title}</span>
Тут тоже самое)

2022-12-30 10:13 UTC, andreevsm commented on src/view/list-item-view.js
> +
Кажется, лишний отступ

2023-01-05 17:48 UTC, andreevsm requested changes

2023-01-05 17:48 UTC, andreevsm commented on src/presenter/events-presenter.js
> +      render(this.#emptyList, this.#eventListComponent.element);
Давай в конце if добавим `return` и тогда от `else` можно будет избавиться)

2023-01-05 17:48 UTC, andreevsm commented on src/view/add-event-view.js
> +function createEditItemTemplate() {
У тебя же тут возвращается новая точка, а не в режиме редактирования, давай переименуем тогда)

2023-01-05 17:48 UTC, andreevsm commented on src/view/add-event-view.js
> +    const selectedType = element.querySelector('input[name="event-type"]:checked').value;
По умолчанию новая точка не может открываться с уже выбранными офферами

2023-01-05 17:48 UTC, andreevsm commented on src/view/offer-view.js
> +function createOfferTemplate(offer) {
Нет необходимости в этом классе, можно сделать просто:
```
function createEditItemTemplate(offers) {
  const offersTemplate = offers.map(offer => {
    return (
      `<div class="event__offer-selector">...</div>`
    )
  }).join('');

  return (
    `              <div class="event__available-offers">
               {offersTemplate}
              </div>`
  )
}
```

2023-01-06 13:35 UTC, Farkhadov95 commented on src/view/add-event-view.js
> +    const selectedType = element.querySelector('input[name="event-type"]:checked').value;
Это для отображения офферов на тип по умолчанию. По умолчанию выбран flight и тут сразу отображаются офферы на flight. Или лучше скрыть офферы вообще?

2023-01-06 15:31 UTC, Farkhadov95 commented on src/view/offer-view.js
> +function createOfferTemplate(offer) {
Для Edit я убрать смог, но вот для Add-event-view так сделать не смог, т.к нужно узнать какой тип установлен по умолчанию.

2023-01-10 08:11 UTC, andreevsm requested changes

2023-01-10 08:11 UTC, andreevsm commented on src/presenter/events-presenter.js
> +      const emptyListMessage = document.querySelector('.trip-events__msg');
Плохая практика в презентере обращаться к DOM элементам
Посмотри как сделано в учебном проекте, там кнопка создания вынесена в main.js, давай также сделаем)

2023-01-10 08:11 UTC, andreevsm commented on src/presenter/events-presenter.js
> +      addNewEventButton.disabled = true;
А это давай пока уберем

2023-01-10 08:11 UTC, andreevsm commented on src/presenter/events-presenter.js
> +      return render(this.#emptyList, this.#eventListComponent.element);
Тоже плохая практика возвращать функцию, которая ничего не возвращает
Давай лучше:
```
render(...);
return;
```

2023-01-10 08:11 UTC, andreevsm commented on src/presenter/events-presenter.js
> +    const addEventComponent = new AddEventView();
Вот эта часть как раз должна уехать в `main.js`

2023-01-10 08:11 UTC, andreevsm commented on src/view/add-event-view.js
> +  function getOffers(selectedType = 'flight') {
1. Раз эта функция не зависит от `createAddItemTemplate`, то можно вынести ее в начало файла
2. Давай переименуем в `createOffersTemplate`

2023-01-10 08:11 UTC, andreevsm commented on src/view/add-event-view.js
> +    const allOffers = offersOnSelectedType.map((offer) => (
Можно сразу `return offersOnSelectedType.map...`

2023-01-10 08:11 UTC, andreevsm commented on src/view/add-event-view.js
> +    const selectedType = element.querySelector('input[name="event-type"]:checked').value;
Эта функция уже не имеет смысла)
Если у выбранного типа нет офферов, то можно просто сделать
```
const offersOnSelectedType = mockOffers.find((offer) => offer.type === selectedType).offers;

if (offersOnSelectedType.length === 0) {
  return ``;
}
```

2023-01-10 08:11 UTC, andreevsm commented on src/view/edit-event-view.js
> +      <input class="event__offer-checkbox  visually-hidden" id="event-offer-${offer.id}" type="checkbox" name="${offer.title}" checked>
Для формы в состоянии редактирования необходимо доработать подсветку офферов: выбранные подсвечиваются синим, а не выбранные - серым
Сейчас получается так, что все подсвечены синим (`checked`)

2023-01-10 08:11 UTC, andreevsm commented on src/view/edit-event-view.js
> +          <p class="event__destination-description">${destination} is a beautiful place.</p>
Всегда в конце будет `is a beautiful place` ?

2023-01-10 08:11 UTC, andreevsm commented on src/presenter/events-presenter.js
> +      if (document.contains(emptyListMessage)) {
А тут по идее просто будет:
```
if (если точек нет) {
  // отрендерить emptyListMessage
  return;
}

// отрендерить точки
```

2023-01-11 17:38 UTC, andreevsm requested changes

2023-01-11 17:38 UTC, andreevsm commented on src/main.js
> +  renderAddEvent(addNewEventButton);
Эта функция не принимает аргументы)

2023-01-11 17:38 UTC, andreevsm commented on src/main.js
> +  const emptyListMessage = document.querySelector('.trip-events__msg');
Смотри, чуть позже будет задание с отображением новой формы
Можешь либо сейчас удалить всю логику, связанную с `addNewEventButton`
Либо пока оставить, но потом весь код здесь придется переделать

2023-01-11 17:38 UTC, andreevsm commented on src/view/add-event-view.js
> +    const selectedType = element.querySelector('input[name="event-type"]:checked').value;
А это почему осталось?)

2023-01-11 17:38 UTC, andreevsm commented on src/view/edit-event-view.js
> +      checked: checked,
Можно просто `checked,`

2023-01-11 17:38 UTC, andreevsm commented on src/view/edit-event-view.js
> +  const offersTemplate = offers.map((offer) => (
В идеале бы этот код вынести в отдельную функцию, чтоб `createEditItemTemplate` была более чистой)

2023-01-11 17:39 UTC, andreevsm commented
Еще момент:
В точке приходят id офферов 1, 2 и 3, но при этом они не подсвечены синим

<img width="1349" alt="Снимок экрана 2023-01-11 в 20 38 23" src="https://user-images.githubusercontent.com/26060516/211878444-99854c2e-5c47-4baa-9381-f4232abbf4c4.png">

2023-01-13 12:03 UTC, merged